version: '3.3'

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://admin:1234@psql_db:5432/missions_db
    depends_on:
      - psql_db
    ports:
      - "5000:5000"
    networks:
      - app_network

  psql_db:
    image: tomer79sagi/wwii_missions
    container_name: psql_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=missions_db
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

